# Form implementation generated from reading ui file '.\layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(746, 510)
        self.wizyta_prywatna = QtWidgets.QCheckBox(parent=Dialog)
        self.wizyta_prywatna.setGeometry(QtCore.QRect(20, 230, 111, 17))
        self.wizyta_prywatna.setChecked(True)
        self.wizyta_prywatna.setObjectName("wizyta_prywatna")
        self.rezerwuj_button = QtWidgets.QPushButton(parent=Dialog)
        self.rezerwuj_button.setGeometry(QtCore.QRect(290, 282, 151, 81))
        self.rezerwuj_button.setObjectName("rezerwuj_button")
        self.result = QtWidgets.QLabel(parent=Dialog)
        self.result.setGeometry(QtCore.QRect(0, 420, 741, 61))
        self.result.setText("")
        self.result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.result.setObjectName("result")
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit.setGeometry(QtCore.QRect(140, 30, 161, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(140, 80, 161, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 130, 101, 65))
        self.widget.setObjectName("widget")
        self.specjalizacja = QtWidgets.QVBoxLayout(self.widget)
        self.specjalizacja.setContentsMargins(0, 0, 0, 0)
        self.specjalizacja.setObjectName("specjalizacja")
        self.internista = QtWidgets.QRadioButton(parent=self.widget)
        self.internista.setChecked(True)
        self.internista.setObjectName("internista")
        self.specjalizacja.addWidget(self.internista)
        self.pediatra = QtWidgets.QRadioButton(parent=self.widget)
        self.pediatra.setObjectName("pediatra")
        self.specjalizacja.addWidget(self.pediatra)
        self.dermatolog = QtWidgets.QRadioButton(parent=self.widget)
        self.dermatolog.setObjectName("dermatolog")
        self.specjalizacja.addWidget(self.dermatolog)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.wizyta_prywatna.setText(_translate("Dialog", "Wizyta prywatna"))
        self.rezerwuj_button.setText(_translate("Dialog", "Rezerwuj"))
        self.label.setText(_translate("Dialog", "imie"))
        self.label_2.setText(_translate("Dialog", "nazwisko"))
        self.internista.setText(_translate("Dialog", "Internista"))
        self.pediatra.setText(_translate("Dialog", "Pediatra"))
        self.dermatolog.setText(_translate("Dialog", "Dermatolog"))
